// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Read the current webhook settings (endpoint, enabled, per-event flags, and a
 * `has_secret` presence flag — never the secret value).
 */
async getSettings() : Promise<Result<WebhookSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:webhook|get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist endpoint/enabled/per-event flags. Does NOT change the secret.
 */
async setSettings(settings: WebhookSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:webhook|set_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store (or replace) the HMAC signing secret in the OS keyring.
 */
async setSecret(secret: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:webhook|set_secret", { secret }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the stored signing secret.
 */
async clearSecret() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:webhook|clear_secret") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recent delivery attempts (newest first), for the settings panel's log view.
 */
async recentDeliveries() : Promise<Result<DeliveryRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:webhook|recent_deliveries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a webhook for `event_type` carrying `payload`.
 * 
 * No-op (returns `Ok(None)`) when: the integration is disabled, no endpoint is
 * configured, no secret is set, or the webhook is not opted-in to
 * `event_type`. On an attempted delivery it returns the `DeliveryRecord` and
 * appends it to the in-memory log.
 */
async sendWebhook(eventType: string, payload: JsonValue) : Promise<Result<DeliveryRecord | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:webhook|send_webhook", { eventType, payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a synthetic `webhook.test` event so the user can validate their
 * endpoint + secret from the settings panel. Ignores per-event opt-in (but
 * still requires an endpoint, a secret, and the master switch enabled).
 */
async testWebhook() : Promise<Result<DeliveryRecord | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:webhook|test_webhook") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * One record in the delivery log.
 */
export type DeliveryRecord = { 
/**
 * Unique delivery id (also sent as `X-Notare-Delivery`).
 */
id: string; 
/**
 * Event type this delivery carried.
 */
event_type: string; 
/**
 * ISO-8601 (RFC 3339) timestamp of the delivery attempt completion.
 */
timestamp: string; 
/**
 * Final HTTP status code, if a response was received.
 */
status_code: number | null; 
/**
 * Error string when delivery failed without a usable response.
 */
error: string | null; 
/**
 * Number of attempts made (1..=max_attempts).
 */
attempts: number; 
/**
 * Whether the delivery ultimately succeeded (2xx response).
 */
success: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Per-event opt-in flags. A webhook only fires for an event whose flag is
 * `true`; everything is off by default (opt-in outbound integration).
 */
export type WebhookEvents = { action_items_updated?: boolean; session_enhanced?: boolean }
/**
 * User-facing webhook configuration. The signing secret is intentionally NOT
 * part of this struct — it lives only in the OS keyring and is never returned
 * to the frontend. `has_secret` reports presence, not the value.
 */
export type WebhookSettings = { 
/**
 * Destination endpoint URL. Empty string means "not configured".
 */
endpoint_url?: string; 
/**
 * Master on/off switch. When false, `send_webhook` is always a no-op.
 */
enabled?: boolean; 
/**
 * Per-event opt-in flags.
 */
events?: WebhookEvents; 
/**
 * Whether a signing secret is currently stored (read-only; never the value).
 */
has_secret?: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
