// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async show() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:dictation|show") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hide() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:dictation|hide") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPhase(phase: Phase) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:dictation|set_phase", { phase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAmplitude(amplitude: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:dictation|update_amplitude", { amplitude }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show the persistent dictation orb window (Windows/Linux webview path;
 * unsupported on macOS, which keeps its native mini-panel).
 */
async showOrb() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:dictation|show_orb") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideOrb() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:dictation|hide_orb") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start a dictation session against the local STT server. `base_url` is the
 * port-bearing URL returned by the local-stt plugin (`http://127.0.0.1:<port>/v1`)
 * and `model` the currently selected live STT model.
 */
async startDictation(baseUrl: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:dictation|start_dictation", { baseUrl, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopDictation() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:dictation|stop_dictation") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether a dictation session is currently running (listening/processing).
 */
async isDictating() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:dictation|is_dictating") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Inject text into the currently focused app. Exposed mainly so the flow can
 * be exercised without a live STT session (devtools/testing).
 */
async typeText(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:dictation|type_text", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
dictationOrbClicked: DictationOrbClicked,
dictationStateEvent: DictationStateEvent,
dictationTranscriptEvent: DictationTranscriptEvent
}>({
dictationOrbClicked: "plugin:dictation:dictation-orb-clicked",
dictationStateEvent: "plugin:dictation:dictation-state-event",
dictationTranscriptEvent: "plugin:dictation:dictation-transcript-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Emitted by the orb webview when the user clicks the orb; the main window
 * host toggles the dictation session in response.
 */
export type DictationOrbClicked = Record<string, never>
/**
 * Lifecycle of the persistent dictation orb (Windows/Linux webview path).
 * Distinct from [`Phase`], which drives the native macOS mini-panel.
 */
export type DictationPhase = 
/**
 * Orb visible, not dictating.
 */
"idle" | 
/**
 * Mic streaming to the local STT server; recognized text is being typed.
 */
"listening" | 
/**
 * Stop requested; waiting for the server to flush the final segments.
 */
"processing" | 
/**
 * The session died (mic/server/injection failure). Cleared on next start.
 */
"error"
/**
 * Broadcast by the Rust dictation session to every webview (the orb window
 * renders it; the main window can observe it to track session state).
 */
export type DictationStateEvent = { phase: DictationPhase; amplitude: number }
/**
 * A final transcript segment that was injected into the focused app.
 */
export type DictationTranscriptEvent = { text: string }
export type Phase = "recording" | "processing"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
