// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async embedAndIndexChunks(sessionId: string, chunks: ChunkInput[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:embedding-search|embed_and_index_chunks", { sessionId, chunks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSessionChunks(sessionId: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:embedding-search|delete_session_chunks", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async semanticSearch(query: string, k: number, sessionId: string | null) : Promise<Result<SearchHit[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:embedding-search|semantic_search", { query, k, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async embeddingIndexStatus() : Promise<Result<IndexStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:embedding-search|embedding_index_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download-on-first-run: fetch the pinned EmbeddingGemma artifacts into the
 * model dir, streaming SHA-256-verified progress over `on_progress`. Idempotent.
 */
async downloadEmbeddingModel(onProgress: TAURI_CHANNEL<DownloadProgress>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:embedding-search|download_embedding_model", { onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * A single text chunk to embed and index.
 */
export type ChunkInput = { 
/**
 * The chunk text to embed.
 */
text: string; 
/**
 * `'note'` | `'transcript'` — which surface this chunk came from.
 */
sourceType: string; 
/**
 * Word-timing anchor (ms into the recording) for transcript chunks; `None`
 * for note chunks.
 */
startMs: number | null; 
/**
 * Hash of the source text at index time; drives idempotent re-index.
 */
contentHash: string }
/**
 * Streaming download progress, emitted per chunk over the command's Channel.
 */
export type DownloadProgress = { 
/**
 * Artifact currently downloading.
 */
file: string; 
/**
 * Bytes of THIS artifact downloaded so far.
 */
file_downloaded: number; 
/**
 * Total bytes of THIS artifact.
 */
file_total: number; 
/**
 * Bytes across ALL artifacts so far.
 */
downloaded: number; 
/**
 * Total bytes across all artifacts.
 */
total: number }
/**
 * Reported by `embedding_index_status`.
 */
export type IndexStatus = { 
/**
 * Whether the model artifacts required to embed are present on disk.
 */
modelDownloaded: boolean; 
/**
 * Number of chunks currently indexed.
 */
chunkCount: number }
/**
 * One semantic search result, chunk metadata plus its distance to the query.
 */
export type SearchHit = { chunkId: string; sessionId: string; sourceType: string; text: string; startMs: number | null; 
/**
 * sqlite-vec L2 distance; smaller is closer.
 */
distance: number }
export type TAURI_CHANNEL<TSend> = null

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
