// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listMeetings(input: ListMeetingsInput) : Promise<Result<MeetingPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|list_meetings", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMeeting(input: GetMeetingInput) : Promise<Result<Meeting, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_meeting", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMeetingTranscript(input: GetMeetingTranscriptInput) : Promise<Result<TranscriptPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_meeting_transcript", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecurringMeetingHistory(input: GetRecurringMeetingHistoryInput) : Promise<Result<MeetingPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_recurring_meeting_history", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async execute(sql: string, params: JsonValue[]) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|execute", { sql, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeTransaction(statements: TransactionStatement[]) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|execute_transaction", { statements }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeProxy(sql: string, params: JsonValue[], method: string) : Promise<Result<ExecuteProxyResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|execute_proxy", { sql, params, method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLegacyImportReport() : Promise<Result<LegacyImportReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_legacy_import_report") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLegacyCleanupStatus() : Promise<Result<LegacyCleanupStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|get_legacy_cleanup_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cleanupLegacyFiles() : Promise<Result<LegacyCleanupResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|cleanup_legacy_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runLegacyImport(dryRun: boolean) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|run_legacy_import", { dryRun }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async subscribe(sql: string, params: JsonValue[], onEvent: TAURI_CHANNEL<QueryEvent>) : Promise<Result<SubscriptionRegistration, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|subscribe", { sql, params, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unsubscribe(subscriptionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|unsubscribe", { subscriptionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncStatus() : Promise<Result<SyncStatusResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|sync_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncTrigger() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|sync_trigger") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncListPeers() : Promise<Result<SyncPeer[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|sync_list_peers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncThisDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|sync_this_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncAddPeer(fingerprint: string, label: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|sync_add_peer", { fingerprint, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncRemovePeer(fingerprint: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|sync_remove_peer", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Runtime opt-in: start the sync agent on an already-running app, without a
 * restart. Idempotent — a no-op if sync is already running.
 */
async syncStart() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|sync_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Runtime opt-out: stop the sync agent while the app keeps running, without
 * a restart. Idempotent — a no-op if sync was never started.
 */
async syncStop() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:db|sync_stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActionItem = { id: string; assignee_human_id: string; status: string; text: string; due_at: string; completed_at: string | null }
export type DependencyAnalysis = { kind: "reactive"; data: { targets: DependencyTarget[] } } | { kind: "non_reactive"; data: { reason: string } }
export type DependencyTarget = { kind: "table"; data: string } | { kind: "virtual_table"; data: string }
export type Document = { id: string; kind: string; template_id: string; title: string; markdown: string; sort_order: number; created_at: string; updated_at: string }
export type ExecuteProxyResult = { rows: JsonValue[] }
export type GetMeetingInput = { meeting_id: string }
export type GetMeetingTranscriptInput = { meeting_id: string; offset: number | null; limit: number | null }
export type GetRecurringMeetingHistoryInput = { meeting_id: string; limit: number | null; offset: number | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LegacyCleanupResult = { deletedFileCount: number; deletedBytes: number }
export type LegacyCleanupStatus = { migrationVerified: boolean; available: boolean; alreadyCleaned: boolean; fileCount: number; totalBytes: number; sourceRoot: string; blockingReason: string | null }
export type LegacyImportItemReport = { sourcePath: string; sourceKind: string; sourceSha256: string; status: string; discoveredCount: number; importedCount: number; matchedCount: number; skippedCount: number; conflictCount: number; error: string }
export type LegacyImportReport = { state: StorageMigrationState; latestRun: LegacyImportRun | null; items: LegacyImportItemReport[]; targets: LegacyImportTargetReport[] }
export type LegacyImportRun = { id: string; importerVersion: number; sourceRoot: string; dryRun: boolean; status: string; discoveredCount: number; importedCount: number; matchedCount: number; skippedCount: number; conflictCount: number; errorCount: number; startedAt: string; completedAt: string | null; error: string }
export type LegacyImportTargetReport = { sourcePath: string; tableName: string; targetId: string; status: string; error: string }
export type ListMeetingsInput = { query: string | null; series_id: string | null; limit: number | null; offset: number | null }
export type Meeting = { id: string; title: string; kind: string; status: string; created_at: string; updated_at: string; started_at: string; ended_at: string; timezone: string; language: string; series_id: string; note: Document | null; summaries: Document[]; participants: Participant[]; action_items: ActionItem[] }
export type MeetingListItem = { id: string; title: string; kind: string; status: string; created_at: string; updated_at: string; started_at: string; ended_at: string; series_id: string }
export type MeetingPage = { meetings: MeetingListItem[]; pagination: Pagination }
export type Pagination = { offset: number; limit: number; returned: number; total: number | null; next_offset: number | null }
export type Participant = { human_id: string; display_name: string; email: string; role: string; job_title: string; organization_id: string; organization_name: string }
export type QueryEvent = { event: "result"; data: JsonValue[] } | { event: "error"; data: string }
export type StorageMigrationState = { phase: string; latestRunId: string; parityVerified: boolean; cutoverAt: string | null; rollbackUntil: string | null; lastError: string; updatedAt: string }
export type SubscriptionRegistration = { id: string; analysis: DependencyAnalysis }
/**
 * Wire shape of a paired peer from the allowlist.
 * 
 * `node_id` stays the compact z32 form (the canonical id — pass it back to
 * `sync_remove_peer`); `fingerprint` is the grouped, dashed display form (the
 * same shape `sync_this_device` / `sync_add_peer` use) for the UI to render.
 */
export type SyncPeer = { nodeId: string; fingerprint: string; label: string; addedAt: number; lastSeen: number }
/**
 * Wire shape of [`hypr_db_core::CloudsyncStatus`] for the specta surface —
 * db-core's own type is serde-only and stays that way (it predates specta
 * and is used by non-tauri consumers); this mirror keeps the boundary.
 */
export type SyncStatusPayload = { cloudsyncEnabled: boolean; extensionLoaded: boolean; configured: boolean; running: boolean; networkInitialized: boolean; lastSyncDownloadedCount: number | null; lastSyncAtMs: number | null; hasUnsentChanges: boolean | null; lastError: string | null; consecutiveFailures: number }
/**
 * The command result for `sync_status`: the live status when sync is built
 * in, or a stub carrying just `cloudsync_enabled: false` otherwise, so the
 * frontend can render one shape in every configuration.
 */
export type SyncStatusResult = ({ kind: "live" } & SyncStatusPayload) | { kind: "unavailable" }
export type TAURI_CHANNEL<TSend> = null
export type TransactionStatement = { sql: string; params: JsonValue[]; expectedRowsAffected?: number | null }
export type TranscriptPage = { meeting_id: string; text: string; words: JsonValue[]; pagination: Pagination }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
