// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async registerHotkey(hotkey: HotKey, options: Options) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:shortcut|register_hotkey", { hotkey, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unregisterHotkey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:shortcut|unregister_hotkey") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register a keyed global hotkey, backed by `tauri-plugin-global-shortcut` on
 * every platform (macOS included, since #31). Several hotkeys can be live at
 * once, each under its own `id` (e.g. the dictation toggle and paste-last
 * hotkeys); re-registering an `id` replaces its previous binding without
 * disturbing the others. Emits `GlobalHotkeyTriggered { id, shortcut }` on
 * key-down.
 */
async registerGlobalHotkey(id: string, shortcut: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:shortcut|register_global_hotkey", { id, shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unregister the keyed global hotkey previously registered under `id`. A no-op
 * if that id has no live binding.
 */
async unregisterGlobalHotkey(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:shortcut|unregister_global_hotkey", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Parse-validate a global-hotkey accelerator string (e.g. "ctrl+alt+space")
 * WITHOUT registering it, so the settings recorder can show inline feedback
 * before committing the `dictation_shortcut` setting.
 */
async parseGlobalHotkey(shortcut: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:shortcut|parse_global_hotkey", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
globalHotkeyTriggered: GlobalHotkeyTriggered,
shortcutEvent: ShortcutEvent
}>({
globalHotkeyTriggered: "plugin:shortcut:global-hotkey-triggered",
shortcutEvent: "plugin:shortcut:shortcut-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Fired when a keyed global hotkey registered via `register_global_hotkey`
 * is pressed, backed by `tauri-plugin-global-shortcut` on every platform.
 * `id` is the caller-chosen registration key (e.g. the dictation toggle
 * vs. paste-last hotkeys), so a single listener can route each press to
 * the right action; `shortcut` is the accelerator string it was bound to.
 * Distinct from `ShortcutEvent`, which is the macOS-only native
 * push-to-talk event-tap path (unused today - see `handler::push_to_talk`).
 */
export type GlobalHotkeyTriggered = { id: string; shortcut: string }
export type HotKey = { key: number | null; modifiers: Modifier[] }
export type Modifier = "command" | "option" | "shift" | "control" | "fn"
export type Options = { useDoubleTapOnly?: boolean; doubleTapLockEnabled?: boolean; minimumKeyTimeMs?: number }
export type ShortcutEvent = { type: "pressed" } | { type: "released" } | { type: "cancelled" } | { type: "discarded" }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
