// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async registerHotkey(hotkey: HotKey, options: Options) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:shortcut|register_hotkey", { hotkey, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unregisterHotkey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:shortcut|unregister_hotkey") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register a toggle-style global hotkey (Windows/Linux). Emits
 * `GlobalHotkeyTriggered` on key-down. Not available on macOS, which keeps
 * its native push-to-talk path.
 */
async registerGlobalHotkey(shortcut: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:shortcut|register_global_hotkey", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unregisterGlobalHotkey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:shortcut|unregister_global_hotkey") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Parse-validate a global-hotkey accelerator string (e.g. "ctrl+alt+space")
 * WITHOUT registering it, so the settings recorder can show inline feedback
 * before committing the `dictation_shortcut` setting. Always Ok on macOS,
 * which keeps its native push-to-talk path and never parses these strings.
 */
async parseGlobalHotkey(shortcut: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:shortcut|parse_global_hotkey", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
globalHotkeyTriggered: GlobalHotkeyTriggered,
shortcutEvent: ShortcutEvent
}>({
globalHotkeyTriggered: "plugin:shortcut:global-hotkey-triggered",
shortcutEvent: "plugin:shortcut:shortcut-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Fired when a toggle-style global hotkey registered via
 * `register_global_hotkey` is pressed (Windows/Linux path, backed by
 * `tauri-plugin-global-shortcut`). Distinct from `ShortcutEvent`, which
 * is the macOS push-to-talk event-tap path.
 */
export type GlobalHotkeyTriggered = { shortcut: string }
export type HotKey = { key: number | null; modifiers: Modifier[] }
export type Modifier = "command" | "option" | "shift" | "control" | "fn"
export type Options = { useDoubleTapOnly?: boolean; doubleTapLockEnabled?: boolean; minimumKeyTimeMs?: number }
export type ShortcutEvent = { type: "pressed" } | { type: "released" } | { type: "cancelled" } | { type: "discarded" }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
