on:
  pull_request:
    paths-ignore:
      - .github/workflows/desktop_ci.yaml
      - apps/cli/**
      - apps/desktop/**
      - plugins/**
      - crates/**
      - Cargo.toml
      - Cargo.lock
permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pass"
